[workspace]
resolver = "2"
members = [
    "crates/cc-core",
    "crates/cc-config",
    "crates/cc-discord",
    "crates/cc-assets",
    "crates/cc-input",
    "crates/cc-render",
    "crates/cc-menu",
    "crates/couchcordd",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/MasonRhodesDev/couchcord"
